<a href="https://colab.research.google.com/github/GeorgeGlennon/Part-II-Chemistry-Programming/blob/Exercise-4/1min1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import math

In [4]:
import numpy as np
import math

def read_coordinates(filepath):
    """A function that reads a .xyz file and returns the molecular coordinates"""
    with open(filepath, 'r') as file:
        lines = file.readlines()
        num_particles = int(lines[0].strip())  # Read number of particles
        coordinates = []

        num_particles = int(lines[0].strip())  # Read number of particles

        for line in lines[2:]:  # Skip the first two lines (header)
            parts = line.split()
            coords = list(map(float, parts[1:]))  # Convert x, y, z to float
            coordinates.append(coords)

    return num_particles, np.array(coordinates)

def Lennard_Jones_potential(r_vec, epsilon=1.0, sigma=1.0):
    """
    Compute Lennard-Jones potential and force for a given vector position.

    Parameters:
    r_vec (np.array): Position vector between two particles.
    epsilon (float): Depth of potential well (default 1.0).
    sigma (float): Distance at which potential is zero (default 1.0).

    Returns:
    V (float): Lennard-Jones potential.
    F_vec (np.array): Force vector (negative gradient of potential).
    """
    r = np.linalg.norm(r_vec)  # Compute distance
    if r == 0:
        raise ValueError("Particles are at the same position, force is undefined.")

    # Compute Lennard-Jones potential
    V = 4 * epsilon * ((sigma / r)**12 - (sigma / r)**6)

    # Compute Lennard-Jones force magnitude
    F_mag = 24 * epsilon * ((2 * (sigma / r)**12) - ((sigma / r)**6)) / r

    # Compute force vector (F = F_mag * (r_vec / r))
    F_vec = -F_mag * (r_vec / r)

    return V, F_vec


class general_potential:
  """A class that performs clauclations on any given potential"""

  def __init__(self, potential):
    self.N, self.coords = read_coordinates("/content/7Hs.txt")
    self.dr = 1e-3
    self.potential = potential

  def get_vectors(self):
    return self.coords[:, np.newaxis, :] - self.coords[np.newaxis, :, :]

  def get_magnitudes(self):
    return np.linalg.norm(self.get_vectors(), axis=-1)

  def get_normalised_vectors(self):
    return self.get_vectors() / self.get_magnitudes()[:, :, np.newaxis]

  def total_energy(self):
    """A function that calculates the total energy of the system"""
    total = 0
    for i in range(self.N-1):
      for j in range(i+1, self.N):
        #print(self.get_magnitudes()[i][j], self.potential(self.get_magnitudes()[i][j]))
        total += (self.potential(self.get_magnitudes()[i][j]))[0]
    return total

  def get_forces(self):
    """"A function that calculates the total force on each particle"""

    vectors = self.get_vectors()
    forces = np.zeros((self.N, 3))  # Initialize force array

    for i in range(self.N):
      for j in range(self.N):
        if i != j:
            _, F_ij = self.potential(vectors[i, j])
            forces[i] += F_ij  # Accumulate force on particle i
    return forces

  def update_coordinates(self):
    forces = self.get_forces()
    coords = self.coords
    print(self.total_energy())
    new_coords = coords - forces * self.dr
    self.coords = new_coords
    return new_coords

  def iterate_to_equilibrium(self):
    n = 0
    while max(np.linalg.norm(f) for f in self.get_forces()) > (self.dr):
    #while n < 50000:
      self.update_coordinates()
      n += 1
    print(f"Equilibrium reached after {n} iterations with an energy of: {self.total_energy()} epsilon")
    return self.coords

  def export_coordinates(self, filepath, element="H"):
    """
    Exports molecular coordinates to a .xyz file.

    Parameters:
    - filepath (str): The output file path.
    - coordinates (np.array): Nx3 array of atomic coordinates.
    - element (str): The atomic element to use for all atoms (default: "H").
    """
    coordinates = self.iterate_to_equilibrium()
    num_atoms = len(coordinates)

    with open(filepath, "w") as file:
        file.write(f"{num_atoms}\n")  # Write the number of atoms
        file.write("Generated by export_coordinates\n")  # Comment line

        for coord in coordinates:
            file.write(f"{element} {coord[0]:.6f} {coord[1]:.6f} {coord[2]:.6f}\n")




general_potential(Lennard_Jones_potential).export_coordinates("/content/output.xyz")

Streaming output truncated to the last 5000 lines.
-12.337500447528752
-12.337506194310993
-12.337511943320262
-12.337517694557913
-12.3375234480253
-12.337529203723783
-12.337534961654718
-12.337540721819467
-12.337546484219397
-12.337552248855859
-12.337558015730231
-12.337563784843868
-12.337569556198135
-12.337575329794404
-12.337581105634042
-12.337586883718425
-12.337592664048909
-12.33759844662688
-12.337604231453696
-12.337610018530746
-12.337615807859398
-12.33762159944103
-12.337627393277012
-12.33763318936873
-12.337638987717568
-12.337644788324894
-12.337650591192105
-12.33765639632057
-12.33766220371169
-12.33766801336683
-12.337673825287386
-12.33767963947475
-12.33768545593031
-12.337691274655452
-12.337697095651572
-12.337702918920055
-12.3377087444623
-12.337714572279705
-12.337720402373652
-12.337726234745563
-12.337732069396806
-12.337737906328805
-12.337743745542953
-12.33774958704064
-12.337755430823286
-12.337761276892287
-12.337767125249053
-12.337772975894978
-1

In [7]:
x = np.zeros((10,3))
x[0] = np.array([1,2,3])

print(x)

[[1. 2. 3.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
