<a href="https://colab.research.google.com/github/GeorgeGlennon/Part-II-Chemistry-Programming/blob/Exercise-4/Dual_Annealing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy.spatial.distance import pdist
from scipy.optimize import dual_annealing
import plotly.graph_objects as go

# Lennard-Jones potential function
def lj_potential(r, epsilon=1.0, sigma=1.0):
    term1 = (sigma / r) ** 12
    term2 = (sigma / r) ** 6
    return 4 * epsilon * (term1 - term2)

# Objective function: Total Lennard-Jones potential for N particles in 3D
def total_lj_energy(coords, N, box_size):
    coords = coords.reshape((N, 3))  # Reshape flat array into (N, 3)

    # Compute pairwise distances in 3D
    distances = pdist(coords)  # Condensed pairwise distance matrix

    # Sum Lennard-Jones potential for each pair
    energy = np.sum(lj_potential(distances))

    return energy

# Number of particles
N = 7  # Number of particles
box_size = 5.0  # Box dimensions
num_restarts = 5  # Number of restarts

# Store the best result
best_result = None

# Run multiple restarts
for _ in range(num_restarts):
    # Initial positions (randomly placed in a cubic box)
    x0 = np.random.uniform(0, box_size, size=(N, 3)).flatten()

    # Bounds: Keep particles within the box
    bounds = [(0, box_size) for _ in range(3 * N)]

    # Run Simulated Annealing (Dual Annealing)
    result = dual_annealing(total_lj_energy, bounds=bounds, args=(N, box_size))

    # Store the best result
    if best_result is None or result.fun < best_result.fun:
        best_result = result

# Extract optimized positions
optimized_coords = best_result.x.reshape((N, 3))

# Print results
print("Optimized Positions:\n", optimized_coords)
print("Minimum Energy:", best_result.fun)

# Create interactive 3D scatter plot using Plotly
fig = go.Figure()

fig.add_trace(go.Scatter3d(
    x=optimized_coords[:, 0],
    y=optimized_coords[:, 1],
    z=optimized_coords[:, 2],
    mode='markers',
    marker=dict(size=6, color='red', opacity=0.8),
    name="Optimized Particles"
))

# Set axis labels
fig.update_layout(
    title="Optimized Particle Positions (Lennard-Jones Potential)",
    scene=dict(
        xaxis_title="X",
        yaxis_title="Y",
        zaxis_title="Z",
    ),
    margin=dict(l=0, r=0, b=0, t=40)
)

# Show interactive plot
fig.show()

<ipython-input-1-aee2cabb4304>:8: RuntimeWarning: divide by zero encountered in divide
  term1 = (sigma / r) ** 12
<ipython-input-1-aee2cabb4304>:9: RuntimeWarning: divide by zero encountered in divide
  term2 = (sigma / r) ** 6
<ipython-input-1-aee2cabb4304>:10: RuntimeWarning: invalid value encountered in subtract
  return 4 * epsilon * (term1 - term2)


Optimized Positions:
 [[4.16903723 2.74440489 2.36939357]
 [3.97913009 3.84997347 2.29711492]
 [3.46704596 3.14504854 1.60104865]
 [2.41753719 2.98715785 1.94348199]
 [2.89664293 4.00000422 2.03388883]
 [3.19946031 3.1720286  2.71683545]
 [3.20392069 2.21115556 2.15083234]]
Minimum Energy: -16.50538416764283
